### ISSUE TITLE
Problem get_fundamentals after Update

### ISSUE THREAD

**Issue by M3rXy** [Jhruzik/finanzen-fundamentals#10]
Hello,

since your last update I am facing the issue, that the stock fundamentals function does not work properly. Before the update I could use the ticker or the full name of the company in `xx.get_fundamentals('Company Name')`. But now that just works sometimes. I could figure out, that it works if the company name has a name without spaces. But the ticker does not work at all and for longer names it doesn't work either. 

The error is the following:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "PATH/lib/python3.8/site-packages/finanzen_fundamentals/stocks.py", line 45, in get_fundamentals_check_site(soup)
  File "PATH/lib/python3.8/site-packages/finanzen_fundamentals/stocks.py", line 28, in _check_site raise ValueError("Could not find Stock")
ValueError: Could not find Stock

Looking for some help.

Best regards

**Comment by Jhruzik** [comment]
That's odd. Do you maybe have an example stock I can look at?
